# --------------------------------------------------
# Configuration
# --------------------------------------------------

MAX_REQUEST_LENGTH = 2000
MAX_RESPONSE_WORDS = 120


# --------------------------------------------------
# User Request Validation
# --------------------------------------------------

def validate_user_request(message: str) -> str:
    """
    Validate and clean the user's message.
    """

    if not message:
        raise ValueError("Message cannot be empty.")

    message = message.strip()

    if not message:
        raise ValueError("Message cannot be empty.")

    if len(message) > MAX_REQUEST_LENGTH:
        raise ValueError(
            "Message is too long."
        )

    return message


# --------------------------------------------------
# LLM Response Validation
# --------------------------------------------------

def validate_llm_response(response: str) -> str:
    """
    Validate the response generated by the LLM.
    """

    if not response:
        raise ValueError(
            "LLM returned an empty response."
        )

    response = response.strip()

    if not response:
        raise ValueError(
            "LLM returned an empty response."
        )

    word_count = len(response.split())

    if word_count > MAX_RESPONSE_WORDS:
        raise ValueError(
            "LLM response exceeds the 120-word limit."
        )

    return response